\set ON_ERROR_STOP on

-- Run as postgres with: psql -d boo_db -v app_password='strong-secret' -f least-privilege.sql
SELECT format('CREATE ROLE boo_app LOGIN PASSWORD %L', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'boo_app')
\gexec

SELECT format('ALTER ROLE boo_app PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION', :'app_password')
\gexec

REVOKE ALL PRIVILEGES ON DATABASE boo_db FROM PUBLIC;
GRANT CONNECT ON DATABASE boo_db TO boo_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO boo_app;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM boo_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO boo_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO boo_app;

ALTER DEFAULT PRIVILEGES FOR ROLE boo_user IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO boo_app;
ALTER DEFAULT PRIVILEGES FOR ROLE boo_user IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO boo_app;
